trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        # Your build commands here
      displayName: 'Build'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        # Your test commands here
      displayName: 'Test'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Your deployment commands here
      displayName: 'Deploy'

- stage: Notify
  jobs:
  - job: NotifyOnSuccess
    displayName: 'Notify on Success'
    dependsOn: [Build, Test, Deploy]
    condition: succeeded()
    steps:
    - script: |
        echo "The CI/CD pipeline completed successfully."

  - job: NotifyOnFailure
    displayName: 'Notify on Failure'
    dependsOn: [Build, Test, Deploy]
    condition: failed()
    steps:
    - script: |
        echo "The CI/CD pipeline failed. Please check the logs."
